#!/usr/bin/env python3
"""Regression suite for render_run.py — the generated resume pointer.

RUN.md exists so a cleared session can tell where a multi-session run stopped.
The whole design rests on one claim: **the pointer is computed, never
remembered**, so it cannot quietly go stale the way a hand-maintained ledger
does. These cases pin that claim:

  - it renders from the machine state + what is on disk, and from nothing else
  - it is a READER: pipeline-state.json is byte-identical after a render
  - the same inputs render byte-identically (no timestamps in the output)
  - --check fails on: missing file, missing stamp (hand-written), stale stamp
  - the verbatim approvals come out of the append-audited state_log unaltered
  - preflight_wave.py refuses a wave when the pointer is stale, and says so

Fixtures are built by calling pipeline_state.py itself where possible, so the
suite exercises the real writer rather than a hand-rolled imitation of it.

    python core/ui-pipeline/tests/run_tests.py

Exit 0 = all green / 1 = failures (each printed). Pure stdlib.
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
RENDER = os.path.join(HERE, "..", "scripts", "render_run.py")
STATE = os.path.join(HERE, "..", "..", "prototyping-ui-directions", "scripts", "pipeline_state.py")
PREFLIGHT = os.path.join(HERE, "..", "..", "anchor-prototype-wave", "scripts", "preflight_wave.py")

failures = []
passed = 0


def run(script, *args):
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    p = subprocess.run([sys.executable, script, *args], capture_output=True, text=True,
                       encoding="utf-8", errors="replace", env=env)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def check(name, cond, detail=""):
    global passed
    if cond:
        passed += 1
        print("ok   %s" % name)
    else:
        print("FAIL %s   %s" % (name, detail))
        failures.append(name)


def make_run(tmp, state_doc=None, files=()):
    """Build a run root; optionally init + patch the machine state, and touch files."""
    root = os.path.join(tmp, "ui-run", "run-a")
    motion = os.path.join(root, "directions", "motion")
    os.makedirs(motion, exist_ok=True)
    for rel in files:
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "w", encoding="utf-8").write("x")
    if state_doc is not None:
        rc, out = run(STATE, "init", "--out-dir", motion, "--run", "run-a")
        assert rc == 0, out
        sp = os.path.join(motion, "pipeline-state.json")
        doc = json.load(open(sp, encoding="utf-8"))
        doc.update(state_doc)
        with open(sp, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(doc, fh, indent=2, ensure_ascii=False)
    return root


def read(p):
    return open(p, encoding="utf-8").read()


# ---------------------------------------------------------------- 1 · no state yet
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp)
    rc, out = run(RENDER, "--run-root", root)
    md = read(os.path.join(root, "RUN.md"))
    check("render: bare run root exits 0", rc == 0, out)
    check("render: stamps no-state when the machine state is absent",
          "<!-- rendered-from: no-state " in md, md[:120])
    check("render: pointer starts at IA round 1",
          "start **IA round 1" in md, md)
    check("render: carries the do-not-hand-edit banner", "GENERATED by" in md)

# ---------------------------------------------------------------- 2 · disk evidence
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp, state_doc={}, files=["ia/info-spec.json", "directions/variant-a/index.html"])
    rc, out = run(RENDER, "--run-root", root)
    md = read(os.path.join(root, "RUN.md"))
    row = [l for l in md.splitlines() if "IA round 1" in l and l.startswith("|")][0]
    check("derive: info-spec.json on disk marks IA round 1 done", "done" in row, row)
    b1 = [l for l in md.splitlines() if "Batch 1" in l and l.startswith("|")][0]
    check("derive: an unlocked variant set is 'in progress', not 'done'",
          "in progress" in b1, b1)
    check("derive: pointer moves to the LEAD pick",
          "your LEAD pick" in md, md)

# ---------------------------------------------------------------- 3 · verbatim approvals
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp, state_doc={})
    motion = os.path.join(root, "directions", "motion")
    sp = os.path.join(motion, "pipeline-state.json")
    quote = u"锁 V5 + Dossier depth，放掉 V1"     # 锁 V5 + Dossier depth，放掉 V1
    rc, out = run(STATE, "approve", "--state-file", sp, "--gate", "chassis",
                  "--approval-text", quote, "--evidence", "test")
    check("fixture: pipeline_state.py approve accepted the quote", rc == 0, out)
    rc, out = run(RENDER, "--run-root", root)
    md = read(os.path.join(root, "RUN.md"))
    check("decisions: the verbatim approval survives into RUN.md unaltered",
          quote in md, md[-600:])
    check("decisions: it is attributed to its gate", "chassis" in md)

# ---------------------------------------------------------------- 4 · reader, and deterministic
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp, state_doc={"state": "CHASSIS_LOCKED", "chassis_locked": True})
    sp = os.path.join(root, "directions", "motion", "pipeline-state.json")
    before = open(sp, "rb").read()
    run(RENDER, "--run-root", root)
    first = read(os.path.join(root, "RUN.md"))
    after = open(sp, "rb").read()
    check("reader: pipeline-state.json is byte-identical after a render", before == after)
    run(RENDER, "--run-root", root)
    check("deterministic: re-rendering the same inputs is byte-identical",
          first == read(os.path.join(root, "RUN.md")))
    rc, out = run(RENDER, "--run-root", root, "--print")
    check("--print writes nothing new and exits 0", rc == 0 and "# RUN" in out, out[:200])

# ---------------------------------------------------------------- 5 · --check
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp, state_doc={})
    sp = os.path.join(root, "directions", "motion", "pipeline-state.json")

    rc, out = run(RENDER, "--run-root", root, "--check")
    check("--check: missing RUN.md blocks", rc == 1 and "no RUN.md" in out, out)

    run(RENDER, "--run-root", root)
    rc, out = run(RENDER, "--run-root", root, "--check")
    check("--check: a fresh render passes", rc == 0 and "current" in out, out)

    doc = json.load(open(sp, encoding="utf-8"))
    doc["composition_ready"] = True
    with open(sp, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(doc, fh, indent=2, ensure_ascii=False)
    rc, out = run(RENDER, "--run-root", root, "--check")
    check("--check: the state moving on makes the pointer STALE",
          rc == 1 and "stale" in out.lower(), out)

    run(RENDER, "--run-root", root)
    rc, out = run(RENDER, "--run-root", root, "--check")
    check("--check: re-rendering clears the staleness", rc == 0, out)

    open(os.path.join(root, "RUN.md"), "w", encoding="utf-8").write("# RUN\n\nhand-written\n")
    rc, out = run(RENDER, "--run-root", root, "--check")
    check("--check: a hand-written pointer with no stamp blocks",
          rc == 1 and "stamp" in out, out)

    rc, out = run(RENDER, "--run-root", os.path.join(tmp, "nope"), "--check")
    check("--check: a missing run root blocks", rc == 1 and "run root not found" in out, out)

# ---------------------------------------------------------------- 6 · the wave gate
with tempfile.TemporaryDirectory() as tmp:
    root = make_run(tmp, state_doc={})
    motion = os.path.join(root, "directions", "motion")
    sp = os.path.join(motion, "pipeline-state.json")

    rc, out = run(PREFLIGHT, "--motion-dir", motion, "--stage", "base-wave")
    check("preflight: no RUN.md is noted, not enforced",
          "no RUN.md" in out and "not started via ui-pipeline" in out, out)

    run(RENDER, "--run-root", root)
    doc = json.load(open(sp, encoding="utf-8"))
    doc["composition_ready"] = True
    with open(sp, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(doc, fh, indent=2, ensure_ascii=False)
    rc, out = run(PREFLIGHT, "--motion-dir", motion, "--stage", "base-wave")
    check("preflight: a stale pointer is a BLOCK reason",
          rc == 1 and "STALE" in out, out)
    check("preflight: the block names the fix command",
          "render_run.py" in out, out)

    open(os.path.join(root, "RUN.md"), "w", encoding="utf-8").write("# RUN\n\nhand-written\n")
    rc, out = run(PREFLIGHT, "--motion-dir", motion, "--stage", "base-wave")
    check("preflight: an unstamped pointer is a BLOCK reason",
          rc == 1 and "rendered-from stamp" in out, out)

# ---------------------------------------------------------------- report
print("---")
if failures:
    print("FAILURES (%d): %s" % (len(failures), ", ".join(failures)))
    sys.exit(1)
print("all green (%d checks)" % passed)
